# Lazy数据源配置
spring:
  datasource:
    meizhuang:
      #url: jdbc:mysql://172.18.26.196:3306/meizhuang?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      #username: java
      #password: 123.com
      url: jdbc:mysql://127.0.0.1:3306/meizhuang?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 500000
      # 校验SQL，Oracle配置 validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 'X'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
      connectionProperties: druid.stat.mergeSql=true;
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true


# DruidDataSource监控登录帐号和密码
druid:
  login:
    username: admin
    password: admin

# 阿里云OSS文件上传
ossBasePath: https://xxxx.oss-cn-xxx.aliyuncs.com/
accessKeyId: LTAInfIxxxxxx
accessKeySecret: oZvASxsjtwCuxxxxxxxx
endpoint: https://oss-cn-hongkong.aliyuncs.com/
bucketName: xxxxzero

# 控制接口暴露的开关
swagger:
  show: true

# 控制短信发送的开关
sms:
  send:
    state: false
# 短信发送签名
    sign: 测试

# 控制银行卡三要素验证的开关
bank:
  card:
    auth:
      state: false
