package com.meizhuang.utils.common;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class IconClass {

	private static List<String> iconList = new ArrayList<String>();

	static {
		iconList.add("layui-icon-reply-fill");
		iconList.add("layui-icon-set-fill");
		iconList.add("layui-icon-menu-fill");
		iconList.add("layui-icon-search");
		iconList.add("layui-icon-share");
		iconList.add("layui-icon-set-sm");
		iconList.add("layui-icon-engine");
		iconList.add("layui-icon-close");
		iconList.add("layui-icon-close-fill");
		iconList.add("layui-icon-chart-screen");
		iconList.add("layui-icon-star");
		iconList.add("layui-icon-circle-dot");
		iconList.add("layui-icon-chat");
		iconList.add("layui-icon-release");
		iconList.add("layui-icon-list");
		iconList.add("layui-icon-chart");
		iconList.add("layui-icon-ok-circle");
		iconList.add("layui-icon-layim-theme");
		iconList.add("layui-icon-table");
		iconList.add("layui-icon-right");
		iconList.add("layui-icon-left");
		iconList.add("layui-icon-cart-simple");
		iconList.add("layui-icon-face-cry");
		iconList.add("layui-icon-face-smile");
		iconList.add("layui-icon-survey");
		iconList.add("layui-icon-tree");
		iconList.add("layui-icon-upload-circle");
		iconList.add("layui-icon-add-circle");
		iconList.add("layui-icon-download-circle");
		iconList.add("layui-icon-templeate-1");
		iconList.add("layui-icon-util");
		iconList.add("layui-icon-face-surprised");
		iconList.add("layui-icon-edit");
		iconList.add("layui-icon-speaker");
		iconList.add("layui-icon-down");
		iconList.add("layui-icon-file");
		iconList.add("layui-icon-layouts");
		iconList.add("layui-icon-rate-half");
		iconList.add("layui-icon-add-circle-fine");
		iconList.add("layui-icon-prev-circle");
		iconList.add("layui-icon-read");
		iconList.add("layui-icon-404");
		iconList.add("layui-icon-carousel");
		iconList.add("layui-icon-help");
		iconList.add("layui-icon-code-circle");
		iconList.add("layui-icon-water");
		iconList.add("layui-icon-username");
		iconList.add("layui-icon-find-fill");
		iconList.add("layui-icon-about");
		iconList.add("layui-icon-location");
		iconList.add("layui-icon-up");
		iconList.add("layui-icon-pause");
		iconList.add("layui-icon-date");
		iconList.add("layui-icon-layim-uploadfile");
		iconList.add("layui-icon-delete");
		iconList.add("layui-icon-play");
		iconList.add("layui-icon-top");
		iconList.add("layui-icon-friends");
		iconList.add("layui-icon-refresh-3");
		iconList.add("layui-icon-ok");
		iconList.add("layui-icon-layer");
		iconList.add("layui-icon-face-smile-fine");
		iconList.add("layui-icon-dollar");
		iconList.add("layui-icon-group");
		iconList.add("layui-icon-layim-download");
		iconList.add("layui-icon-picture-fine");
		iconList.add("layui-icon-link");
		iconList.add("layui-icon-diamond");
		iconList.add("layui-icon-log");
		iconList.add("layui-icon-rate-solid");
		iconList.add("layui-icon-fonts-del");
		iconList.add("layui-icon-unlink");
		iconList.add("layui-icon-fonts-clear");
		iconList.add("layui-icon-triangle-r");
		iconList.add("layui-icon-circle");
		iconList.add("layui-icon-radio");
		iconList.add("layui-icon-align-center");
		iconList.add("layui-icon-align-right");
		iconList.add("layui-icon-align-left");
		iconList.add("layui-icon-loading-1");
		iconList.add("layui-icon-return");
		iconList.add("layui-icon-fonts-strong");
		iconList.add("layui-icon-upload");
		iconList.add("layui-icon-dialogue");
		iconList.add("layui-icon-video");
		iconList.add("layui-icon-headset");
		iconList.add("layui-icon-cellphone-fine");
		iconList.add("layui-icon-add-1");
		iconList.add("layui-icon-face-smile-b");
		iconList.add("layui-icon-fonts-html");
		iconList.add("layui-icon-form");
		iconList.add("layui-icon-cart");
		iconList.add("layui-icon-camera-fill");
		iconList.add("layui-icon-tabs");
		iconList.add("layui-icon-fonts-code");
		iconList.add("layui-icon-fire");
		iconList.add("layui-icon-set");
		iconList.add("layui-icon-fonts-u");
		iconList.add("layui-icon-triangle-d");
		iconList.add("layui-icon-tips");
		iconList.add("layui-icon-picture");
		iconList.add("layui-icon-more-vertical");
		iconList.add("layui-icon-flag");
		iconList.add("layui-icon-loading");
		iconList.add("layui-icon-fonts-i");
		iconList.add("layui-icon-refresh-1");
		iconList.add("layui-icon-rmb");
		iconList.add("layui-icon-home");
		iconList.add("layui-icon-user");
		iconList.add("layui-icon-notice");
		iconList.add("layui-icon-voice");
		iconList.add("layui-icon-upload-drag");

		iconList.add("layui-icon-snowflake");
		iconList.add("layui-icon-file-b");
		iconList.add("layui-icon-template");
		iconList.add("layui-icon-auz");
		iconList.add("layui-icon-console");
		iconList.add("layui-icon-app");
		iconList.add("layui-icon-prev");
		iconList.add("layui-icon-website");
		iconList.add("layui-icon-next");
		iconList.add("layui-icon-component");
		iconList.add("layui-icon-more");
		iconList.add("layui-icon-shrink-right");
		iconList.add("layui-icon-spread-left");
		iconList.add("layui-icon-camera");
		iconList.add("layui-icon-note");
		iconList.add("layui-icon-refresh");
		iconList.add("layui-icon-female");
		iconList.add("layui-icon-male");
		iconList.add("layui-icon-password");
		iconList.add("layui-icon-senior");
		iconList.add("layui-icon-theme");
		iconList.add("layui-icon-tread");
		iconList.add("layui-icon-praise");
		iconList.add("layui-icon-star-fill");
		iconList.add("layui-icon-rate");
		iconList.add("layui-icon-template-1");
		iconList.add("layui-icon-vercode");
		iconList.add("layui-icon-cellphone");
		iconList.add("layui-icon-screen-full");
		iconList.add("layui-icon-screen-restore");
		iconList.add("layui-icon-cols");
		iconList.add("layui-icon-export");
		iconList.add("layui-icon-print");
		iconList.add("layui-icon-slider");
		// iconList.add("layui-icon-login-wechat");
		// iconList.add("layui-icon-login-qq");
		// iconList.add("layui-icon-login-weibo");
	}

	public static String getIcon() {
		return iconList.get(new Random().nextInt(iconList.size()));
	}

}
